name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - add-diy4_2-sensors-and-capabilities

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v1

      - name: Deploy docs
        uses: elauber/airgradient_mqtt@add-diy4_2-sensors-and-capabilities
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}